{% set name = "hub" %}
{% set version = "2.4.0" %}
{% set sha256 = "894eb112be9aa0464fa2c63f48ae8e573ef9e32a00bad700e27fd09a0cb3be4b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/github/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - go >=1.8
  host:
    - posix  # [win]
  run:

test:
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - hub version

about:
  home: https://github.com/github/hub
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'git + hub = github'

  description: |
    hub is a command line tool that wraps git in order to extend it with
    extra features and commands that make working with GitHub easier.
  dev_url: https://github.com/github/hub

extra:
  recipe-maintainers:
    - sodre
