{% set name = "hub" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/github/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 35fecdbcaf0afb6b7273a160cc169f76ec62b95105037ac3fc833b24573f9a4f
  folder: src/github.com/github/hub

build:
  number: 1000

requirements:
  build:
    - {{ compiler('c') }}
    - go >=1.8
  host:
    - posix  # [win]
  run:

test:
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - hub version

about:
  home: https://github.com/github/hub
  license: MIT
  license_family: MIT
  license_file: src/github.com/github/hub/LICENSE
  summary: 'git + hub = github'

  description: |
    hub is a command line tool that wraps git in order to extend it with
    extra features and commands that make working with GitHub easier.
  dev_url: https://github.com/github/hub

extra:
  recipe-maintainers:
    - sodre
    - asford
