{% set name = "hub" %}
{% set version = "2.5.0" %}
{% set sha256 = "8e3bda092ddc81eaf208c5fd2b87f66e030012129d55fa631635c6adf8437941" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/github/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  folder: src/github.com/github/hub

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - go >=1.8
  host:
    - posix  # [win]
  run:

test:
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - hub version

about:
  home: https://github.com/github/hub
  license: MIT
  license_family: MIT
  license_file: src/github.com/github/hub/LICENSE
  summary: 'git + hub = github'

  description: |
    hub is a command line tool that wraps git in order to extend it with
    extra features and commands that make working with GitHub easier.
  dev_url: https://github.com/github/hub

extra:
  recipe-maintainers:
    - sodre
