# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DO2qG+Ng79G5ZkSY/RtiuCm9yHhWqNkW1jaDxGjEQ3SjDetNrPdP0ht1KHo0z5vHTv6h1XM7FZiAYJWTiQSSBwEAHI2PbwS2nGQQ8z/Mg4EKOIebsGzG/kbLKkJ4SluJXh84GVnKd0jzvfBPYFgyurarGrG7/Ar+/nBfODc/KirXNH5EHfws8rzvaNNrcDDJBVKsAUk2rjNYVgyGZO1xRe5KW3jExxD/zsRTWXIQZuVvZxs7MSAsjZ2JMbTYGs/XTtHAFrlQovrZ2tdWFBGQlWO5CRhV1WKMdvmJpYtltp2Cp5OwTil2WIP28Wa89tR8goKynXmiluYr8BqT572DoRu5b7+8iQb1OF80AHVg7u5P8IhlFCzmYtkDcv1dplbamxbQsHgcevBf+E/o260m0IfUiYqCvsV32AlMT2UCSNf+I11wZNR2LFHYIsTg3rdVmhObD+CWgC00McgeX/SXUoLGBKeGQ+KD3JxSGPVX+YNkSnOcAt91t1hg9d+54fhFHy9Hn33m6rQ/i3LNNtLtQ8KO2LXGYghAjhoudEWJUqH2clj9JT7EjLz0MSyZPUaDK07V9jhFZRUkmUAntigKzpE1UX+pel8ngi70mNsNfKU2ahd7q8k/9UPCFbWfh055M3znnoNrCD03lGir8Ef6HIcQ2DwhMD6yUT9637rGVn0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml