travis:
  secure:
    BINSTAR_TOKEN: klrkLExPoiLB1SXK9IMfHdb+Uw9TlCMc2T1VazfN6H6c9HjHnoJUQs9m3XW1j9FiNU1vYo0cutuUKjJ4xlVouVnY91ASS7JP8ciy5T/DOgfWfe8x2u1VIq7FLb2DOVEm3Dv5N4K0sxabvw14GjoF18Fjjeka6htBbPijLyXe/8Bsnx6bnFe0KA0Z77aOrLdOfz008JhDyBW2xSNYjNgNSmd2YfhAIfXWfrnge6fbMJ+UZGo/atFvFEprFhfoRE0u0aLDqOceFoorcqKrd5xvnDWWqusSbcabJzjICrvoRQHc7liCERtAmnvdbTwS2BNbtY4szx4SfUJbDFAd1RRbksD78u3BOZO/H/sxSJ/05NyYkQn+R6gRZK4rg9ctOv4np7VaFO/hyiXzf597KZZaz/kpyfW6Ny+FbdvzOsQOhji0f6PwWed4Lw4hMl+jr7WR3EC2bh3xIa/BIQ2WWX0PtmQ+1GjFnsuFpYOWeFVpcYk4D4Ur82L7APMbz2U4v71qd4p9GK6pShm4UzGlST6Us4xLDjJdDDawlUAEynwSoqX2HGPXIVdnGOoCHv8pZQn3JRZpzqBX/MagrNPjPmQUy6vD4hrNMABduwyyeSsTSXCAEM10Qs6aypDHmMVdF4hIc451nxH+lk514olM/kozYslqeZW4Qopg43Q4n7aKzDE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
