appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DO2qG+Ng79G5ZkSY/RtiuCm9yHhWqNkW1jaDxGjEQ3SjDetNrPdP0ht1KHo0z5vHTv6h1XM7FZiAYJWTiQSSBwEAHI2PbwS2nGQQ8z/Mg4EKOIebsGzG/kbLKkJ4SluJXh84GVnKd0jzvfBPYFgyurarGrG7/Ar+/nBfODc/KirXNH5EHfws8rzvaNNrcDDJBVKsAUk2rjNYVgyGZO1xRe5KW3jExxD/zsRTWXIQZuVvZxs7MSAsjZ2JMbTYGs/XTtHAFrlQovrZ2tdWFBGQlWO5CRhV1WKMdvmJpYtltp2Cp5OwTil2WIP28Wa89tR8goKynXmiluYr8BqT572DoRu5b7+8iQb1OF80AHVg7u5P8IhlFCzmYtkDcv1dplbamxbQsHgcevBf+E/o260m0IfUiYqCvsV32AlMT2UCSNf+I11wZNR2LFHYIsTg3rdVmhObD+CWgC00McgeX/SXUoLGBKeGQ+KD3JxSGPVX+YNkSnOcAt91t1hg9d+54fhFHy9Hn33m6rQ/i3LNNtLtQ8KO2LXGYghAjhoudEWJUqH2clj9JT7EjLz0MSyZPUaDK07V9jhFZRUkmUAntigKzpE1UX+pel8ngi70mNsNfKU2ahd7q8k/9UPCFbWfh055M3znnoNrCD03lGir8Ef6HIcQ2DwhMD6yUT9637rGVn0=}
provider:
  win: azure
